function skillsMember() {
  return {
    name: 'Member',
    skills: [
      'C++',
      'Python',
      'Java',
      'JavaScript',
      'React',
      'Node.js',
      'Docker',
      'Kubernetes',
      'AWS',
      'Azure',
      'GCP',
      'SQL',
      'NoSQL',
      'Git',
      'CI/CD',
      'Agile',
      'Scrum',
      'Kanban',
      'TDD',
      'BDD',
      'DDD',
      'Microservices',
      'REST',
      'GraphQL',
      'Kafka',
      'RabbitMQ',
      'Redis',
      'MongoDB',
      'PostgreSQL',
      'MySQL',
      'Linux',
      'Windows',
      'macOS',
      'VS Code',
      'IntelliJ',
      'Eclipse',
      'Jenkins',
      'Travis CI',
      'Circle CI',
      'GitHub Actions',
      'Jira',
      'Confluence',
      'Slack',
      'Teams',
      'Zoom',
      'WebEx',
      'Google Meet',
      'Docusaurus',
      'Gatsby',
      'Next.js',
      'NestJS',
      'Spring Boot',
      'Express',
      'Flask',
      'Django',
      'TensorFlow',
      'PyTorch',
      'Keras',
      'Scikit-learn',
      'Pandas',
      'NumPy',
      'Matplotlib',
      'Seaborn',
      'Plotly',
      'Jupyter',
      'Docker Compose',
      'Kubernetes Helm',
      'Terraform',
      'Pulumi',
      'Ansible',
      'Chef',
      'Puppet',
      'Prometheus',
      'Grafana',
      'ELK',
      'Splunk',
      'Datadog',
      'New Relic',
      'Sentry',
      'Postman',
      'Swagger',
      'OpenAPI',
      'gRPC',
      'REST Assured',
      'Jest',
      'Mocha',
      'Chai',
      'Cypress',
      'Selenium',
      'Appium',
      'Jasmine',
      'Karma',
      'Junit',
      'TestNG',
      'Mockito',
      'PowerMock',
      'EasyMock',